### ISSUE TITLE
com.hmily.tcc.common.bean.entity.Participant转换错误

### ISSUE THREAD

**Issue by Avengervick** [yu199195/hmily#69]
有人遇到过这种情况吗？

2018-12-19 16:00:36.044 [hmilyTransaction-tccRollBackService-1] ERROR com.hmily.tcc.core.schedule.ScheduledService - execute recover exception:com.hmily.tcc.common.bean.entity.Participant cannot be cast to com.hmily.tcc.common.bean.entity.Participant
java.lang.ClassCastException: com.hmily.tcc.common.bean.entity.Participant cannot be cast to com.hmily.tcc.common.bean.entity.Participant
	at com.hmily.tcc.core.schedule.ScheduledService.cancel(ScheduledService.java:135)
	at com.hmily.tcc.core.schedule.ScheduledService.lambda$0(ScheduledService.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Avengervick** [comment]
![y8 4l3d534a6u 5s m974](https://user-images.githubusercontent.com/18612691/50206905-e2bd7680-03a7-11e9-96ad-1eec2cf7d1ec.png)

**Comment by Avengervick** [comment]
> 使用最新代码。。。明显是你的类加载器不正确
那我拉master分支编译可以吗

**Comment by yu199195** [comment]
可以使用master分支
